# Generated by Django 4.2.5 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=100)),
                ('data', models.TextField(default='')),
                ('dataset', models.CharField(max_length=100)),
            ],
        ),
    ]
