version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "12007:80"
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - app

  app:
    build: .
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - using_docker=1
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8001

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-demo
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./systems/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.xml
    restart: unless-stopped

  gan:
    build: ./generation
    container_name: gan_container
    volumes:
      - ./generation/data:/app/data
      - ./generation/results:/app/results
      - ./generation/run_pretrained.py:/app/run_pretrained.py
    ports:
      - "87:80"
    restart: unless-stopped



volumes:
  static_volume:
  clickhouse_data:


